kind: "Template"
apiVersion: "v1"
metadata:
  name: "cvmanager-template"
  annotations:
    description: "Template for cvmanager service"
labels:
  template: "cvmanager-template"
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: cvmanagerapp
      namespace: kube-system
      labels:
        app: cvmanager
    spec:
      replicas: 1
      revisionHistoryLimit: 15
      selector:
        matchLabels:
          app: cvmanager
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
      minReadySeconds: 30
      template:
        metadata:
          labels:
            app: cvmanager
            component: cvmanagerapp
        spec:
          nodeSelector:
            node-role.kubernetes.io/master: ""
          tolerations:
            - key: "node-role.kubernetes.io/master"
              effect: NoSchedule
          containers:
            - name: cvmanagerapp-container
              image: nearmap/cvmanager:$(VERSION)
              ports:
                - containerPort: 20419
              args:
                - "run"
                - "--configmap-key=kube-system/cvmanager"
              env:
              - name: INSTANCENAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: STATS_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: AWS_REGION
                valueFrom:
                  configMapKeyRef:
                    name: cvmanager
                    key: region
  - kind: ConfigMap
    apiVersion: v1
    data:
      region: "$(REGION)"
      version: $(VERSION)
    metadata:
      name: cvmanager
      namespace: kube-system
parameters:
  - name: "REGION"
    description: "AWS region name"
    required: true
    parameterType: "string"
    value: "ap-southeast-2"
  - name: "ENV"
    description: "Name of the cluster"
    required: true
    parameterType: "string"
  - name: "VERSION"
    description: "version of the application for deployment"
    required: true
    parameterType: "string"
